### ISSUE TITLE
Bump OpenCV version?

### ISSUE THREAD

**Issue by AI-Passionner** [JaidedAI/EasyOCR#1022]
EasyOCr is great. 
However, its OpenCV version is not compatible with other packages. I am wondering if you guys can bump the OpenCV to 4.6.0 or even higher.

Currently, I got an error message, which I don't know how to go around 
""""
[AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)](https://stackoverflow.com/questions/72706073/attributeerror-partially-initialized-module-cv2-has-no-attribute-gapi-wip-gs)
""""

**Comment by niallmc** [comment]
I have the exact same issue, and I rely on a recent version of OpenCV, would be great if this can be updated to support later OpenCV version.

**Comment by rdavis22** [comment]
@AI-Passionner The way I am currently get around it is creating a new environment in Anaconda and installing the packages in an order that doesn't break my environment. This typically involves putting 'easyocr' near the bottom. I am not familiar with docker so this is the order of install from Anaconda Prompt for my environment (reading WSIs for pathology):

	1) torch
	2) openslide
	3) easyocr (pip)
	4) matplotlib (pip)
	5) pandas (pip)

**Comment by r-remus** [comment]
This has been fixed in the latest release, i.e. v1.7.0, which now doesn't require a specific OpenCV version anymore.

**Comment by Yury-MonZon** [comment]
Still doesn't work with the latest pipy version nor github version. Tried multiple opencv versions as well.
