### ISSUE TITLE
Bad Batch OCR Performance

### ISSUE THREAD

**Issue by Siegi96** [JaidedAI/EasyOCR#534]
Using a RTX 6000 (24 gb VRAM), I can perform ~15-20 images(n_width=1080, n_height=1919) in parallel without running into CUDA memory issues. However, processing the images sequentially is ~20% faster, even the GPU usage is lower than in parallel mode. I always pass the already downloaded pictures into easyocr, so the performance loss is within the OCR system for sure. Whats the threshold when readtext_batched is faster than processing images sequentially and do you know any reasons which could cause this performance loss?

**Comment by rkcosmos** [comment]
@SamSamhuns

**Comment by SamSamhuns** [comment]
@Siegi96, are you using the EasyOCR GitHub repo from the latest commit, or did you use the release 1.4 pip installation?

**Comment by Siegi96** [comment]
@SamSamhuns I'm using the 1.4 pip installation.

**Comment by SamSamhuns** [comment]
Can you try with the latest GitHub commit instead (`git clone https://github.com/JaidedAI/EasyOCR`)?

There was an issue with the 1.4 release mentioned here #474 related to the batched inference which is fixed in the latest GitHub repo.

**Comment by Siegi96** [comment]
For several reasons I will wait for the PIP release and inform you, if the fix solved my issue. Maybe I will find some time to test the latest Git Version on another machine.

**Comment by Siegi96** [comment]
@SamSamhuns 1.4.1 (including the fix of [https://github.com/JaidedAI/EasyOCR/issues/474](474) ) did not solve the problem. Even during testing with clean test scripts on Google Colab, I did not experience any performance gains when using the readtext_batched() with pre-downloaded images. I also tried your test script on both, Colab and my GPU Server and also could not see any performance gains using batched ocr. 😬

**Comment by SamSamhuns** [comment]
@Siegi96, the thing is, to get a faster batch performance, you need to inference a lot of images at once (The script you used might have had a batch of 3, I use 15 now), when I try the example inference setup from the Google Colab [here](https://colab.research.google.com/drive/1YvwjTBKdrtLXF-Ez9mlgr2MBo2lmNYhl?usp=sharing), I do get better-batched performance. You can try running the same google collab to see what you get.

![Screen Shot 2021-09-20 at 6 15 32 PM](https://user-images.githubusercontent.com/13418507/134018093-876249be-449d-44ec-ae6e-eb880f94ff92.png)

Additionally, I have mentioned in my PR that one needs to do some warmup inferences on the batched easyOCR for it to be faster otherwise its speed will not be faster than the sequential inference.

 The best use case for the batched inference would be on large sets of images of the same size with the same batch between inferences or on a **video**. Hope this helps :)

**Comment by anshumansinha16** [comment]
I am trying to use the batch inference for my OCR processing, but it seems like I am not getting any performance gain when going from batch_size = 50 to batch_size = 100. the GPU memory utilization has evidently doubled, but there is no gain in total processing time.
