### ISSUE TITLE
error when reading an png

### ISSUE THREAD

**Issue by MicalKarl** [JaidedAI/EasyOCR#640]
```
Traceback (most recent call last):
  File "testocr.py", line 5, in <module>
    result = reader.readtext('1.png')
  File "C:\Users\karl\Desktop\test\venv\lib\site-packages\easyocr\easyocr.py", line 385, in readtext
    horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
  File "C:\Users\karl\Desktop\test\venv\lib\site-packages\easyocr\easyocr.py", line 275, in detect
    text_box_list = get_textbox(self.detector, img, canvas_size, mag_ratio,
  File "C:\Users\karl\Desktop\test\venv\lib\site-packages\easyocr\detection.py", line 95, in get_textbox
    bboxes_list, polys_list = test_net(canvas_size, mag_ratio, detector,
  File "C:\Users\karl\Desktop\test\venv\lib\site-packages\easyocr\detection.py", line 55, in test_net
    boxes, polys, mapper = getDetBoxes(
  File "C:\Users\karl\Desktop\test\venv\lib\site-packages\easyocr\craft_utils.py", line 236, in getDetBoxes
    boxes, labels, mapper = getDetBoxes_core(textmap, linkmap, text_threshold, link_threshold, low_text, estimate_num_chars)
  File "C:\Users\karl\Desktop\test\venv\lib\site-packages\easyocr\craft_utils.py", line 31, in getDetBoxes_core
    nLabels, labels, stats, centroids = cv2.connectedComponentsWithStats(text_score_comb.astype(np.uint8), connectivity=4)
cv2.error: Unknown C++ exception from OpenCV code
```

**Comment by Aslyamovt** [comment]
Same problem with all images

```
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_9312/3775422832.py in <module>
      1 s = time.time()
----> 2 result = reader.readtext(path)
      3 print(time.time()-s)

D:\Anaconda\envs\ocr\lib\site-packages\easyocr\easyocr.py in readtext(self, image, decoder, beamWidth, batch_size, workers, allowlist, blocklist, detail, rotation_info, paragraph, min_size, contrast_ths, adjust_contrast, filter_ths, text_threshold, low_text, link_threshold, canvas_size, mag_ratio, slope_ths, ycenter_ths, height_ths, width_ths, y_ths, x_ths, add_margin, output_format)
    383         img, img_cv_grey = reformat_input(image)
    384 
--> 385         horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
    386                                                  low_text, link_threshold,\
    387                                                  canvas_size, mag_ratio,\

D:\Anaconda\envs\ocr\lib\site-packages\easyocr\easyocr.py in detect(self, img, min_size, text_threshold, low_text, link_threshold, canvas_size, mag_ratio, slope_ths, ycenter_ths, height_ths, width_ths, add_margin, reformat, optimal_num_chars)
    273             img, img_cv_grey = reformat_input(img)
    274 
--> 275         text_box_list = get_textbox(self.detector, img, canvas_size, mag_ratio,
    276                                     text_threshold, link_threshold, low_text,
    277                                     False, self.device, optimal_num_chars)

D:\Anaconda\envs\ocr\lib\site-packages\easyocr\detection.py in get_textbox(detector, image, canvas_size, mag_ratio, text_threshold, link_threshold, low_text, poly, device, optimal_num_chars)
     92     result = []
     93     estimate_num_chars = optimal_num_chars is not None
---> 94     bboxes_list, polys_list = test_net(canvas_size, mag_ratio, detector,
     95                                        image, text_threshold,
     96                                        link_threshold, low_text, poly,

D:\Anaconda\envs\ocr\lib\site-packages\easyocr\detection.py in test_net(canvas_size, mag_ratio, net, image, text_threshold, link_threshold, low_text, poly, device, estimate_num_chars)
     52 
     53         # Post-processing
---> 54         boxes, polys, mapper = getDetBoxes(
     55             score_text, score_link, text_threshold, link_threshold, low_text, poly, estimate_num_chars)
     56 

D:\Anaconda\envs\ocr\lib\site-packages\easyocr\craft_utils.py in getDetBoxes(textmap, linkmap, text_threshold, link_threshold, low_text, poly, estimate_num_chars)
    234     if poly and estimate_num_chars:
    235         raise Exception("Estimating the number of characters not currently supported with poly.")
--> 236     boxes, labels, mapper = getDetBoxes_core(textmap, linkmap, text_threshold, link_threshold, low_text, estimate_num_chars)
    237 
    238     if poly:

D:\Anaconda\envs\ocr\lib\site-packages\easyocr\craft_utils.py in getDetBoxes_core(textmap, linkmap, text_threshold, link_threshold, low_text, estimate_num_chars)
     29 
     30     text_score_comb = np.clip(text_score + link_score, 0, 1)
---> 31     nLabels, labels, stats, centroids = cv2.connectedComponentsWithStats(text_score_comb.astype(np.uint8), connectivity=4)
     32 
     33     det = []

error: Unknown C++ exception from OpenCV code
```
Conda environment: 
```
# packages in environment at D:\Anaconda\envs\ocr:
#
# Name                    Version                   Build  Channel
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
ca-certificates           2021.10.8            h5b45459_0    conda-forge
importlib-resources       5.4.0                    pypi_0    pypi
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
jupyter-client            7.1.0                    pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-core              4.9.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.2                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib-inline         0.1.3                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
nest-asyncio              1.5.4                    pypi_0    pypi
opencv-python             4.5.5.62                 pypi_0    pypi
opencv-python-headless    4.5.5.62                 pypi_0    pypi
prometheus-client         0.12.0                   pypi_0    pypi
prompt-toolkit            3.0.24                   pypi_0    pypi
python-bidi               0.4.2                    pypi_0    pypi
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
scikit-image              0.19.1                   pypi_0    pypi
```

**Comment by Aslyamovt** [comment]
@MicalKarl solved this problem by opencv-python-headless и opencv-python of version 4.5.1.48

**Comment by MicalKarl** [comment]
> @MicalKarl solved this problem by opencv-python-headless и opencv-python of version 4.5.1.48

It works!

**Comment by xuyichenmo** [comment]
It workss!!!!

**Comment by egeres** [comment]
I was getting the same issue (which hadn't happened before, I have no idea how this broke out of nowhere)

Fixed it with the `opencv-python-headless==4.5.1.48` @Aslyamovt short of mentioned and was changed in https://github.com/xuyichenmo/EasyOCR/commit/3333f241349ddaf45477cc1bcda768da56d338dd

**Comment by Furippu24** [comment]
Hi all, 
I am getting the same issue, but issue does not fix by changing opencv-python-headless and opencv-python versions to either 4.5.1.48 nor 4.5.4.60. 

`Traceback (most recent call last):
  File "C:\Users\fish\AppData\Local\Programs\Python\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 9, in <module>
  File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\easyocr.py", line 385, in readtext
    horizontal_list, free_list = self.detect(img, min_size, text_threshold,\
  File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\easyocr.py", line 275, in detect
    text_box_list = get_textbox(self.detector, img, canvas_size, mag_ratio,
  File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\detection.py", line 95, in get_textbox
    bboxes_list, polys_list = test_net(canvas_size, mag_ratio, detector,
  File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\detection.py", line 55, in test_net
    boxes, polys, mapper = getDetBoxes(
  File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\craft_utils.py", line 236, in getDetBoxes
    boxes, labels, mapper = getDetBoxes_core(textmap, linkmap, text_threshold, link_threshold, low_text, estimate_num_chars)
  File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\craft_utils.py", line 31, in getDetBoxes_core
    nLabels, labels, stats, centroids = cv2.connectedComponentsWithStats(text_score_comb.astype(np.uint8), connectivity=4)
cv2.error: Unknown C++ exception from OpenCV code
`

`
click                  8.0.4
colorama               0.4.4
cycler                 0.11.0
easyocr                1.4.1
fonttools              4.29.1
imageio                2.9.0
joblib                 1.1.0
kiwisolver             1.3.2
lmdb                   1.3.0
matplotlib             3.5.1
natsort                8.1.0
networkx               2.6.3
NEURON                 8.0
nltk                   3.7
numpy                  1.22.2
opencv-python          4.5.1.48
opencv-python-headless 4.5.1.48
packaging              21.3
pandas                 1.4.1
pdf2image              1.16.0
Pillow                 8.2.0
pip                    22.0.3
plotly                 5.6.0
pyparsing              3.0.7
python-bidi            0.4.2
python-dateutil        2.8.2
pytz                   2021.3
PyWavelets             1.2.0
PyYAML                 6.0
regex                  2022.1.18
scikit-image           0.19.2
scipy                  1.8.0
setuptools             57.0.0
six                    1.16.0
tenacity               8.0.1
tifffile               2022.2.9
torch                  1.10.2
torchaudio             0.10.2
torchvision            0.11.3
tqdm                   4.62.3
typing_extensions      4.1.1
wheel                  0.36.2
`

**Comment by Furippu24** [comment]
> Hi all, I am getting the same issue, but issue does not fix by changing opencv-python-headless and opencv-python versions to either 4.5.1.48 nor 4.5.4.60.
> 
> `Traceback (most recent call last): File "C:\Users\fish\AppData\Local\Programs\Python\Python39\lib\code.py", line 90, in runcode exec(code, self.locals) File "<input>", line 9, in <module> File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\easyocr.py", line 385, in readtext horizontal_list, free_list = self.detect(img, min_size, text_threshold,\ File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\easyocr.py", line 275, in detect text_box_list = get_textbox(self.detector, img, canvas_size, mag_ratio, File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\detection.py", line 95, in get_textbox bboxes_list, polys_list = test_net(canvas_size, mag_ratio, detector, File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\detection.py", line 55, in test_net boxes, polys, mapper = getDetBoxes( File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\craft_utils.py", line 236, in getDetBoxes boxes, labels, mapper = getDetBoxes_core(textmap, linkmap, text_threshold, link_threshold, low_text, estimate_num_chars) File "C:\Users\fish\PycharmProjects\PDFOCR\venv\lib\site-packages\easyocr\craft_utils.py", line 31, in getDetBoxes_core nLabels, labels, stats, centroids = cv2.connectedComponentsWithStats(text_score_comb.astype(np.uint8), connectivity=4) cv2.error: Unknown C++ exception from OpenCV code `
> 
> `click 8.0.4 colorama 0.4.4 cycler 0.11.0 easyocr 1.4.1 fonttools 4.29.1 imageio 2.9.0 joblib 1.1.0 kiwisolver 1.3.2 lmdb 1.3.0 matplotlib 3.5.1 natsort 8.1.0 networkx 2.6.3 NEURON 8.0 nltk 3.7 numpy 1.22.2 opencv-python 4.5.1.48 opencv-python-headless 4.5.1.48 packaging 21.3 pandas 1.4.1 pdf2image 1.16.0 Pillow 8.2.0 pip 22.0.3 plotly 5.6.0 pyparsing 3.0.7 python-bidi 0.4.2 python-dateutil 2.8.2 pytz 2021.3 PyWavelets 1.2.0 PyYAML 6.0 regex 2022.1.18 scikit-image 0.19.2 scipy 1.8.0 setuptools 57.0.0 six 1.16.0 tenacity 8.0.1 tifffile 2022.2.9 torch 1.10.2 torchaudio 0.10.2 torchvision 0.11.3 tqdm 4.62.3 typing_extensions 4.1.1 wheel 0.36.2`

Sorry, I just had "WARNING: Ignoring invalid distribution" for opencv packages ~ working now

**Comment by nqx12348** [comment]
> @MicalKarl solved this problem by opencv-python-headless и opencv-python of version 4.5.1.48

I meet the same problem, and it works to use opencv-python==4.5.1.48.  Thanks!
